version: "3.4"
services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: db_jobart
    ports:
      - "3308:3306"
    networks:
      - generation-network
  jobart-api:
    restart: always
    build: ./jobart-api
    working_dir: /jobart-api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./jobart-api:/jobart-api
      - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - generation-network
networks:
  generation-network:
    driver: bridge